// Regenerates src/render/fonts.generated.ts and assets/OFL.txt from the pinned devDependency
// @expo-google-fonts/noto-sans. Fonts are embedded as base64 so rendering never touches the
// filesystem at runtime (works under any bundler). Run: pnpm --filter @ai-career/document-export embed-fonts
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const packageDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const fontDir = path.join(packageDir, "node_modules", "@expo-google-fonts", "noto-sans");

const regular = readFileSync(path.join(fontDir, "400Regular", "NotoSans_400Regular.ttf")).toString("base64");
const bold = readFileSync(path.join(fontDir, "700Bold", "NotoSans_700Bold.ttf")).toString("base64");

const header =
  "// GENERATED by scripts/embed-fonts.mjs -- do not edit. Noto Sans (Regular, Bold), SIL Open Font License 1.1\n" +
  "// (see assets/OFL.txt), from @expo-google-fonts/noto-sans@0.4.2.\n";
writeFileSync(
  path.join(packageDir, "src", "render", "fonts.generated.ts"),
  `${header}export const NOTO_SANS_REGULAR_BASE64 =\n  "${regular}";\nexport const NOTO_SANS_BOLD_BASE64 =\n  "${bold}";\n`
);

mkdirSync(path.join(packageDir, "assets"), { recursive: true });
copyFileSync(path.join(fontDir, "LICENSE_FONT"), path.join(packageDir, "assets", "OFL.txt"));
console.log("wrote src/render/fonts.generated.ts and assets/OFL.txt");
